### ISSUE TITLE
py2dsp fails with local sdist

### ISSUE THREAD

**Issue by mr-c** [p1otr/pypi2deb#15]
(Thanks for this great tool!)

This is with the latest `pypi2deb` in Debian sid.

```
$ py2dsp ~/src/CTDopts/dist/CTDopts-1.1.tar.gz 
W: py2dsp pypi:54: cannot download CTDopts None details from PyPI: ContentTypeError("0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8'",)
/usr/share/pypi2deb/pypi2deb/pypi.py:58: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  session is not None and session.close()
E: py2dsp base_events:1266: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3a55da9da0>
E: py2dsp base_events:1266: Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f3a5cfa94e0>, 9091.023025117)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f3a55b229e8>
E: py2dsp py2dsp:145: 'name'
```
`~/src/CTDopts/dist/CTDopts-1.1.tar.gz ` was created via `python setup.py sdist` inside https://github.com/WorkflowConversion/CTDopts

**Comment by sandrotosi** [comment]
i think we still need the project to exist on PyPI, since that's where the tool fetches some of the the metadata

**Comment by sandrotosi** [comment]
as said above, the source package needs to exist on PyPI, so that we can fetch its metadata, required to populate some of the package data. i see there's https://github.com/WorkflowConversion/CTDopts/issues/26 to do so, hence i'd suggest proceeding with addressing that issue and then retry.

I believe this bug can be closed as not-a-bug
